### ISSUE TITLE
Meta thread of UI/UX improvements to make to Snikket iOS

### ISSUE THREAD

**Issue by distefam** [snikket-im/snikket-ios#10]
As discussed in the #general chat, Snikket iOS has a non-standard user interface that appears unfamiliar and "janky" to many iOS users, who have come to expect a level of consistency among iOS applications. This is partly due to Apple's (in)famous [HIG](https://developer.apple.com/design/human-interface-guidelines/), ui/ux standards that evolved in a development culture that was originally heavily influenced by small independent developers who valued attention to UI/UX detail (see flexibits, tapbots, tweetie, etc.), and general conventions adopted by related apps.

This thread attempts to summarize key improvements that can be made to the Snikket iOS client to make it feel more "at home" on Apple's mobile OS. It is my personal opinion, based partly on observations of the reactions of friends and family who have installed and use Snikket on iOS, that _the interface of Snikket iOS should closely resemble similar apps until at least the main bugs are worked out_. In other words, **innovate where it matters: in providing a secure and decentralized messaging experience where you control your server and/or data.** Messaging interfaces are largely a solved problem at this point. That isn't to say there is no room for improvement but that _having a non-standard interface is going to frighten away users who would otherwise have given Snikket a shot_.

The following will begin as a non-exhaustive list of key issues that I believe will have the biggest impact when addressed, however, it will grow as others suggest UI/UX improvements.

### 1. Chat Compose View
The chat compose view is cramped and the buttons for adding attachments are too small. Nearly all other messaging apps on iOS have the same basic compose interface: a rounded input field with buttons to add attachments and one to send.
- [ ] Replace input field with standard rounded-rect input field found in other messaging apps (#23)
- [ ] Increase icon sizes to more standard size (#16)
- [ ] Consolidate icons into an expandable general one for attachments (#16)
- [ ] Change icons to ones used more commonly for this purpose. [Glyphish](https://www.glyphish.com/) icons are commonly used by iOS developers but there are others as well.

### 2. Pull-to Refresh #22 
iOS has a built-in pull-to-refresh mechanism that is activated by pulling _down_ in a list view. This displays a standard animated spinner at the top of the list view, though that can be customized to be a flying Snikket (see Twitter's flying bird animation) for example.

Snikket currently activates pull-to-refresh by swiping _up_ in the list view. This is non-standard and un-expected. 

Also, when pulling to refresh it pulls in old messages that may have been encrypted for a previous device. This leads to a host of OMEMO error messages showing up in one's history.

### 3. Distinguish sent from received messages #21 
There are many ways to handle this, the most common being colored chat bubbles. Most, if not all, messaging apps have the avatar beside sent and received messages be on opposite sides of the screen as well.

Right now, it is very difficult to at-a-glance distinguish between sent and received messages.

---

This list will continue to expand to eventually be an exhaustive list of UI/UX issues that could be fixed before a general release. I will pull each out into its own issue and reference those issues here when I get a chance.

**Comment by distefam** [comment]
Closing this meta ticket as I have filed individual tickets for each item above. Also, it makes more sense to use Github's release milestone metadata to track those issues to fix before a release than doing so via a meta-ticket.
